# ModSecurity Lite Console - StopBadBots
# Default configuration file

ACCESS_LOG=/usr/local/apache/logs/access_log
MODSEC_AUDIT_LOG=/usr/local/apache/logs/modsec_audit.log
REFRESH_INTERVAL=20
TOP_LIMIT=10
